export enum ProductAvailabilityState {
  TIME_CLUSTER = 'TIME_CLUSTER',
  PARTIAL_AVAILABLE = 'PARTIAL_AVAILABLE',
  AVAILABLE = 'AVAILABLE',
  NOT_AVAILABLE = 'NOT_AVAILABLE',
  LOWERTHRESHOLD = 'LOWERTHRESHOLD',
  UPPERTHRESHOLD = 'UPPERTHRESHOLD',
  NOONLINESTOCK = 'NOONLINESTOCK',
  RELEASE = 'RELEASE',
  PICKUP_TIMERANGE = 'PICKUP_TIMERANGE',
  NOT_POSSIBLE_IN_CITY_CENTER = 'NOT_POSSIBLE_IN_CITY_CENTER',
  NOT_POSSIBLE_IN_GENERAL = 'NOT_POSSIBLE_IN_GENERAL',
}
