export enum ProductOnlineStatus {
  UNKNOWN = 'UNKNOWN',
  PERMANENTLY_NOT_AVAILABLE = 'PERMANENTLY_NOT_AVAILABLE',
  CURRENTLY_NOT_AVAILABLE = 'CURRENTLY_NOT_AVAILABLE',
  NOT_YET_AVAILABLE = 'NOT_YET_AVAILABLE',
  AVAILABLE = 'AVAILABLE',
}
